# Generated by Django 4.1.1 on 2022-10-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin')], max_length=50),
        ),
    ]
