# Generated by Django 4.1.1 on 2022-10-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_name_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
