# Generated by Django 4.1.1 on 2022-10-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_borrower_details_issued_by_alter_user_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('ENGINEERING', 'ENGINEERING'), ('COMMERCE', 'COMMERCE'), ('ARTS', 'ARTS')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=5),
        ),
    ]
