# Generated by Django 4.1.1 on 2022-10-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_department_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('ENGINEERING', 'ENGINEERING'), ('COMMERCE', 'COMMERCE'), ('ARTS', 'ARTS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=5),
        ),
    ]
