# Generated by Django 4.1.1 on 2022-10-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_details',
            name='publication_year',
            field=models.DateField(),
        ),
    ]
