# Generated by Django 4.1.1 on 2022-10-11 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_book_details_publication_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(default=0)),
                ('borrowed_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
