# Generated by Django 4.1.1 on 2022-10-11 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_duepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duepayment',
            name='borrowed_detail',
        ),
        migrations.AddField(
            model_name='duepayment',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book_detail', to='users.book_details'),
        ),
        migrations.AddField(
            model_name='duepayment',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower_detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duepayment',
            name='overdue_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book_detail', to='users.borrower_details'),
        ),
    ]
