# Generated by Django 4.1.1 on 2022-10-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_duepayment_amount_paid_remove_duepayment_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duepayment',
            name='overdue_amount',
        ),
        migrations.AddField(
            model_name='duepayment',
            name='amount_to_be_paid',
            field=models.IntegerField(default=0),
        ),
    ]
