# Generated by Django 4.1.1 on 2022-10-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_duepayment_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duepayment',
            name='book',
        ),
    ]
